### ISSUE TITLE
Increase maximum dpi export

### ISSUE THREAD

**Issue by alexpacini** [badgeek/svg2shenzhen#54]
I tried to modify
```
<param name="dpi" type="int" min="0" max="2000" _gui-text="Export DPI (default: 600)">600</param>
```
to 
```
<param name="dpi" type="int" min="0" max="10000" _gui-text="Export DPI (default: 600)">600</param>
```
and the export was super fine.
Is there any reason to limit the dpi to 2000?
I see it is quite impossible to manufacture a pcb with higher resolution, but for some niche application it might be ok to have a higher limit.
I tried to go over 10000, but the number of lines in the footprint didn't change, so maybe the upper limit is 10000.

**Comment by twinkletwinkie** [comment]
My pull request the other day updated the max from 2,000 to 3,600.  The reason for that limit vs 10,000 is simply because no fab supports such high resolutions in the first place and at 1,200 most artifacts that may be caused by exporting at 600 DPI are addressed which is why as of 0.2.18.2 the default resolution is 1,200.   Going above 3,600 only increases the file size of the part & gerbers and does not provide greater fidelity in the end product.
