### ISSUE TITLE
exception in simplepath.py

### ISSUE THREAD

**Issue by philtrick-twm** [badgeek/svg2shenzhen#62]
Hi, I have just installed the extension and I'm getting the following error:

Traceback (most recent call last):
  File "prepare.py", line 11, in <module>
    import simplepath, simpletransform
  File "/usr/share/inkscape/extensions/simplepath.py", line 51
    raise Exception, 'Invalid path data!'
                   ^
SyntaxError: invalid syntax

This is on Fedora31 with Inkscape 0.92

**Comment by farnstrom** [comment]
I had this problem too (as well as a bunch of others to deal with, like the Inkscape-1.0-beta RPM on Fedora 31 not including the extensions). I figured out how to fix it. The problem is that in Fedora 31 Python 3 is the default, which seems to not work with this extension. I followed the instructions here: https://wiki.inkscape.org/wiki/index.php/Extension_Interpreters, pointing to /usr/bin/python2.7, and it seems to work now, so far at least.
