### ISSUE TITLE
Error with Inskcape 1.0 beta and Catalina MacOS

### ISSUE THREAD

**Issue by sabas1080** [badgeek/svg2shenzhen#67]
Hi 

I am using the lastet version of inskcape because I have MacOS Catalina, i have the next error in export kicad

```
export.py:224: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--path", action="store", type="string", dest="path", default="~/", help="")
export.py:225: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-f', '--filetype', action='store', type='string', dest='filetype', default='jpeg', help='Exported file type')
export.py:226: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--crop", action="store", type="inkbool", dest="crop", default=False)
export.py:227: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--dpi", action="store", type="float", dest="dpi", default=600)
export.py:228: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--threshold", action="store", type="float", dest="threshold", default=128.0)
export.py:229: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--openfactory", action="store", type="inkbool", dest="openfactory", default="true")
export.py:230: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--openkicad", action="store", type="inkbool", dest="openkicad", default="true")
export.py:231: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--autoflatten", action="store", type="inkbool", dest="autoflatten", default="true")
export.py:232: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--debug", action="store", type="inkbool", dest="debug", default=False)
export.py:748: DeprecationWarning: Effect.affect is now `Effect.run()`. The `output` argument has changed.
  e.affect()
export.py:347: DeprecationWarning: self.args[-1] is now self.options.input_file
  curfile = self.args[-1]
Traceback (most recent call last):
  File "export.py", line 752, in <module>
    _main()
  File "export.py", line 748, in _main
    e.affect()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/deprecated.py", line 181, in affect
    return self.run(args=args)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/base.py", line 123, in run
    self.save_raw(self.effect())
  File "export.py", line 324, in effect
    self.processExportLayer()
  File "export.py", line 348, in processExportLayer
    layers = self.get_layers(curfile)
  File "export.py", line 548, in get_layers
    if  layer_label_name in self.layer_map.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'
```

Thanks

**Comment by liquidcitymotors** [comment]
Hello! I experienced this same error and additional issues on MacOS 10.14 with version 1.0rc1. Everything was working perfectly before updating Inkscape. 

It seems like the major version update has broken some things. The following changes in export.py were enough to get a working export. I figured I would share the details in case it helped anyone before the extension is fully updated to be 1.0 compatible.

Line 548, change to:
``if  layer_label_name in self.layer_map.keys():``

385:
``with open(options_path, 'rb') as f:``

396:
``with open(options_path, 'wb') as f:``

Those three seemed like python 2 vs 3 issues.

397:
``pickle.dump(options, f)`` throws an exception because of the type of the "output" option. I believe this could be better resolved by updating the deprecated methods. I ended up pickling a dict with the relevant options and changing the syntax of the prev_options line. Probably not the best.

Those changes properly exported the drill and edge cut layers.

Then, to get the other layers, the export to PNG section needed tweaks because it seems like the command line arguments for Inkscape changed.

Line 595:
``area_param = '-D' if self.options.crop else '-C'`` (the C was missing a dash not sure if that matters)
Line 596:
``command = "inkscape %s -d %s -o \"%s\" \"%s\"" % (area_param, int(self.options.dpi), output_path, svg_path)`` (-e was changed to -o, DPI seems to need to be an integer)

Also for MacOS, I needed to relink the inkscape command to the new location (~/Inkscape.app/Contents/MacOS) per [this page](https://stackoverflow.com/questions/22085168/inkscape-command-line-where-is-it-on-mac).

Now I can use this awesome tool with the shiny new native MacOS app 😄 I'd be happy to share the edited file if anyone wants to take a look.

**Comment by rcludwick** [comment]
Looks like it needs to be:  if layer_label_name in self.layer_map

**Comment by AEFeinstein** [comment]
I'm seeing this on Windows as well, with the Inkscape 1.0 release (not beta).

**Comment by HebrewzHammer** [comment]
> 
> 
> I'm seeing this on Windows as well, with the Inkscape 1.0 release (not beta).

Same here.

Looks like Inkscape v1.0 now uses Python 3 instead of 2. So svg2shenzhen will need to be updated to work with Python 3.

The "iterkeys" is a simple fix, but the next issue is it's trying to use pickle on an object that contains file objects, which won't work. I haven't taken a close look, but it's probably an easy fix since I doubt svg2shenzhen actually cares about those file objects being pickled.

Also, there's a way to override Inkscape to use Python 2, but it's not really a simple fix (see https://wiki.inkscape.org/wiki/index.php?title=Extension_Interpreters). It's easy to get Inkscape to use Python 2, but you'll have to have it installed somewhere since v1.0 doesn't bring it along anymore. Also, you'll need to manually install all the modules svg2shenzhen needs (honestly it's not a lot). However, depending on what Python 2 version you have installed you might still run into the pickle issue again. I tried a quick and dirty hack to get around it (using the "dill" module instead) which seemed to work (still got a bunch of deprecation warnings) but the output KiCad project only had the edge cuts layer there, so obviously that hack isn't going to work.

**Comment by HebrewzHammer** [comment]
Just saw this has already been discussed in #64 and #49 .
